### ISSUE TITLE
Blackout of stars

### ISSUE THREAD

**Issue by paddy-exe** [paddy-exe/GodotStylizedSkyShader#5]
There seems to be a spot dependant on the camera view which blocks the stars. Will need to investigate further to check out the cause
![image](https://user-images.githubusercontent.com/38077837/212202240-fc001ba7-6b07-449a-9c2a-2aa9979990ce.png)

**Comment by Mikeysax** [comment]
@paddy-exe I've fixed this but not have had a moment to make a PR

**Comment by paddy-exe** [comment]
> @paddy-exe I've fixed this but not have had a moment to make a PR

Wow awesome Mike! Looking forward to the PR. No hurries though

**Comment by paddy-exe** [comment]
Fixed by https://github.com/paddy-exe/GodotStylizedSkyShader/pull/6
